### ISSUE TITLE
LogicException in Panel

### ISSUE THREAD

**Issue by diephi3** [bvdputte/kirby-logbook#2]
Exactly the plugin I was looking for. 
Unfortunately a Bug occurred on my local server.

I'm running:
Kirby 3.6.1.1 (modified from plainkit)
PHP 8.1.1
Local environment is Valet-Linux secured by TLS (php8.1-fpm, nginx)

After I installed the Plugin I can no longer login to the Panel and the error.logbook.internal is thrown when going to mySite.test/panel.

Interestingly when I install the Plugin WHILE logged in, I can access the newly created View in the Panel and the Plugin seems to be working fine. Same error is then prompted the moment I click the logout button in the Panel.
Other than that the front end without panel seems to be working.
The moment I remove the Plugin from required and `composer update` the Panel is accessible again.

```
Kirby\Exception\LogicException thrown with message "This task cannot be finished"

Stacktrace:
#12 Kirby\Exception\LogicException in /myKirbyFolder/site/plugins/kirby-logbook/classes/Logbook.php:147
#11 bvdputte\kirbyLogbook\Logbook:hasAccess in /myKirbyFolder/site/plugins/kirby-logbook/areas.php:7
```
Greetings, diephi.
I hope I'm not bothering you with an internal setup problem on my side.

**Comment by bvdputte** [comment]
Thanks for reporting @diephi3 .

Should be fixed 👍
